#
#This is the package wide initialization file.
#
#Use to set configure what is imported on a * import, and for other package
#wide tasks.


# package wide logging.
import logging
#import logging.handlers
logger = logging.getLogger(name=__name__)
# re-set this in a script to globally change the log level.
logger.setLevel(logging.WARNING)
# avoid collecting too much info
logging._srcfile = None
logging.logThreads = 0
logging.logProcesses = 0
# a standard handler
console_handler = logging.StreamHandler()
logger.addHandler(console_handler)
std_fmt = logging.Formatter("%(levelname)s:%(name)s: %(message)s")
console_handler.setFormatter(std_fmt)
# SPEED: still, all log messages of all levels are actually generated by
# default (just not read and formatted).
# AVOID PUTTING DEBUG MESSAGES INTO HOT LOOPS!


#global error classes
class NIError(Exception):
    '''"not implemented"'''
    pass
